version: '3.8'
services:
  gas-water-publisher:
    environment: 
      - RTLTCP_SERVER=192.168.1.156:1234
      - VERBOSE=true
      - MQTT_HOST=192.168.1.1
    restart: unless-stopped
    build: 
      context: .


